version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_URI=mongodb://admin:password@localhost:27017/fee_collector
    networks:
      - fee-collector-network
    restart: unless-stopped

  fee-collector:
    image: fee-collector-image
    container_name: fee-collector-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    networks:
      - fee-collector-network
    depends_on:
      - mongodb
    restart: always

networks:
  fee-collector-network:

volumes:
  db:
